### ISSUE TITLE
Improving the user profile's display

### ISSUE THREAD

**Issue by Abhiram-Gullapalli** [Pradumnasaraf/OctoUser#1]
### Description

I've spotted this small bug, which is not actually one, but improving it would be great. In case there is a successful search of a github profile and a new search is done which is invalid account, the profile image doesn't get updated, instead the previously searched profile's image is displayed.
Hope you understood what I was trying to convey.

**Comment by Pradumnasaraf** [comment]
Thank you so much for opening the issue and reporting it :tada:  @Abhiram-Gullapalli. It's fixed now

Happy, Open Source
