### ISSUE TITLE
[FEATURE] Create @MediaQueries so the page is responsive!

### ISSUE THREAD

**Issue by abitsalihu** [Pradumnasaraf/OctoUser#11]
### Description

I noticed that the website is not responsive at all. I would love to be able and work on this. :)
In tho photo it shows what the website looks on small screens.

### Screenshots

<img width="1437" alt="Screen Shot 2022-09-04 at 15 35 48" src="https://user-images.githubusercontent.com/94648837/188316503-0e036980-2721-4b67-9ffd-cf6d824706c2.png">

**Comment by abitsalihu** [comment]
I just noticed there is an open pull request on this topic, my apologies.

**Comment by Pradumnasaraf** [comment]
No worries, thank you so much for the issue :)
