### ISSUE TITLE
Spcaing issue betwen the elements

### ISSUE THREAD

**Issue by Pradumnasaraf** [Pradumnasaraf/OctoUser#16]
### Description

There should be space between the elements like the search box and button in the mobile view

### Screenshots

<img width="391" alt="Screenshot 2023-01-30 at 5 47 13 PM" src="https://user-images.githubusercontent.com/51878265/215475240-97305980-fba4-4994-b0de-979356c1b1b7.png">

**Comment by shyamtawli** [comment]
Hey @Pradumnasaraf I like to work on it. Please assign.

**Comment by Pradumnasaraf** [comment]
Yes go ahead.
