### ISSUE TITLE
[DOCS] Add contributing guidelines

### ISSUE THREAD

**Issue by Pradumnasaraf** [Pradumnasaraf/OctoUser#4]
### Description

Add step by step contributing guidelines in `CONTRIBUTING.md`

**Comment by omogidi** [comment]
Hello. i would like to work on this.

**Comment by Pradumnasaraf** [comment]
> Hello. i would like to work on this.

Yes, go ahead. Thank you!

**Comment by deeproop** [comment]
hello, I would like to contribute to this issue.

**Comment by omogidi** [comment]
Hello Prad.

I have created a pull request. Please review and merge

**Comment by Arman-ali-khan-786** [comment]
i would like to work on it bro ,you can check one of my repo for the same,https://github.com/Arman-ali-khan-786/CardUI

**Comment by Pradumnasaraf** [comment]
Closes in 5e3efa51fe8ab8220de32d56d1d27980906b38a0
