### ISSUE TITLE
[Bug] Website is not responsive

### ISSUE THREAD

**Issue by droy117** [Pradumnasaraf/OctoUser#5]
### Description

The texts go outside the box. Please check the screenshots below.

### Screenshots

![Screenshot_2022-08-14-10-20-55-797_com android chrome](https://user-images.githubusercontent.com/104914725/184523660-b3d36069-710a-44ab-be22-a7244baada2b.jpg)
![Screenshot_2022-08-14-10-20-33-406_com android chrome](https://user-images.githubusercontent.com/104914725/184523662-b4901fe3-725b-46b4-89b9-d3ca21f17dc1.jpg)

**Comment by Pradumnasaraf** [comment]
Thank you @slayeh17 for reporting. Yes, we knew that it's not mobile responsive.

**Comment by WIZN0DE** [comment]
> Thank you @slayeh17 for reporting. Yes, we knew that it's not mobile responsive.

Oh, should I close this issue or keep it open? 
Actually, this is my first time reporting an issue so am a little confused🥲.

**Comment by Pradumnasaraf** [comment]
> > Thank you @slayeh17 for reporting. Yes, we knew that it's not mobile responsive.
> 
> Oh, should I close this issue or keep it open? This is my first time reporting an issue so am a little confusedsmiling_face_with_tear.

No no. leave it open. You did 1000% correct by opening it, this is how people will come to what things in the project are lacking and contribute to.
Thank you so much and good luck with your Open Source journey :)

**Comment by WIZN0DE** [comment]
Thank You @Pradumnasaraf

**Comment by Andyy-18** [comment]
Hey @Pradumnasaraf bro!
I'm also a newbie :)
I have modified your code a little bit to make the website responsive.
Pls checkout.
It's my first contribution.

**Comment by 3xp11i** [comment]
Hello @Pradumnasaraf , Kindly check my PR, I have made the website responsive and have done some good changes for the same purpose. Hope you like it!

**Comment by 3xp11i** [comment]
Hey @Pradumnasaraf, did you check my PR?

**Comment by KendallDoesCoding** [comment]
@Andyy-18 @prakhartiwari2507 - I really appreciate that yall are interested in contributing, but please request to be assigned first before you create a PR.

Just a practice you should have for open-source projects :)) but I'm sure @Pradumnasaraf won't mind this time.

Thanks,
KendallDoesCoding

**Comment by 3xp11i** [comment]
@Pradumnasaraf If you are there kindly check if the changes I have made are good or if they need more changes. Thanks

**Comment by Pradumnasaraf** [comment]
> @Pradumnasaraf If you are there kindly check if the changes I have made are good or if they need more changes. Thanks

Hey. I was busy with other projects and didn't know how notifications got muted for this project. The other person's PR didn't get merged so will be merging your PR tomorrow

**Comment by 3xp11i** [comment]
> > @Pradumnasaraf If you are there kindly check if the changes I have made are good or if they need more changes. Thanks
> 
> Hey. I was busy with other projects and didn't know how notifications got muted for this project. The other person's PR didn't get merged so will be merging your PR tomorrow

No problem @Pradumnasaraf, thanks for giving your time. I am happy to contribute to this project.
One request, if you can please, then guide me more on how to get better in the open source world and create a good profile.

**Comment by 3xp11i** [comment]
I hope you don't forget about this today also @Pradumnasaraf

**Comment by Pradumnasaraf** [comment]
> > > @Pradumnasaraf If you are there kindly check if the changes I have made are good or if they need more changes. Thanks
> > 
> > 
> > Hey. I was busy with other projects and didn't know how notifications got muted for this project. The other person's PR didn't get merged so will be merging your PR tomorrow
> 
> No problem @Pradumnasaraf, thanks for giving your time. I am happy to contribute to this project. One request, if you can please, then guide me more on how to get better in the open source world and create a good profile.

Thanks,
- Do code review.
- Push small changes
- Join the Open Source community and contribute to them, like EddieHub

**Comment by Pradumnasaraf** [comment]
> I hope you don't forget about this today also @Pradumnasaraf

No, I will not :)

**Comment by hemantwasthere** [comment]
Hey @Pradumnasaraf, I would like to work on this issue. Please assign it to me

**Comment by Pradumnasaraf** [comment]
> Hey @Pradumnasaraf, I would like to work on this issue. Please assign it to me

Please don't spam below every issue

**Comment by anuragh2002** [comment]
Hey @Pradumnasaraf is this issue open? If yes, I would like to work on it. Thanks!

**Comment by anuragh2002** [comment]
Hey @Pradumnasaraf I centered the images and created a pull request. Kindly review it!

**Comment by E-fais** [comment]
This is still open, I believe. 
@Pradumnasaraf  please assign me this issue

**Comment by Pradumnasaraf** [comment]
Sorry I dint have the look at the look, as @anuragh2002 commented 1st I will let him go.

**Comment by Pradumnasaraf** [comment]
Issue Fixed
